plugins {
    id 'com.android.application'
    id 'com.google.gms.google-services'
}

android {
    namespace 'com.bgconnect.gestor'
    compileSdk 35

    defaultConfig {
        applicationId 'com.bgconnect.gestor'
        minSdk 24
        targetSdk 35
        versionCode 4
        versionName '1.3.0'
    }
}

dependencies {
    implementation 'com.google.firebase:firebase-messaging:24.1.0'
}
